### ISSUE TITLE
Webserver source code

### ISSUE THREAD

**Issue by coolhva** [ShaneNolan/Runsome#1]
Dear Shane,

I really like your ransomware client (for educational purposes). I've seen that the backend (php) is relatively easy to build but it would save some time for other people if you are able post it next to this repository.

Could you consider doing it so we can all benefit from your work? Thanks in advance!

Kind regards,

Henk

**Comment by ShaneNolan** [comment]
@coolhva Oh, I completely forgot to do that! Yeah the PHP is pretty basic but I will definately upload it in the next repository.
Thanks for your kind words.

Regards,
Shane 👍
