### ISSUE TITLE
frmmain

### ISSUE THREAD

**Issue by megaborg** [ShaneNolan/Runsome#2]
Hello, i builder runsome in any cpu and x86, runsome crypt my file (in virtualbox) and ok,
the problem is in frmmain, won't show jigsaw and here a two days, win10 x86, 
I also tried another computer with Windows 10 x86 and get the same result can not see the frmMain

**Comment by ShaneNolan** [comment]
Jigsaw doesn't popup until all the personal files have been encrypted.

**Comment by megaborg** [comment]
ok ty

**Comment by megaborg** [comment]
ok ty =)
